apiVersion: v1
kind: Service
metadata:
  name: locust
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8089
  selector:
    statefulset.kubernetes.io/pod-name: locust-0
    app: locust
